#!/usr/bin/env bash
set -e

type pytest > /dev/null \
    || { echo 'Please install pytest for python2 via pip.'
         echo 'On ubuntu xenial run:: `pip2 install pip && pip2 install --user pytest`'
         exit 1
       }

progress() { echo ==== "$@" ; }

source /opt/ros/kinetic/setup.bash # TODO: This path is Ubuntu specific
export PATH="$(pwd)/rosmop/bin:$PATH"

progress "Building rosmop"
(cd rosmop ; mvn -q package -DskipTests)

progress "Building src"
catkin_make -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON

export ROS_MASTER_URI="http://localhost:11311/"
export REAL_MASTER_URI="http://localhost:20022/"
export ACCESS_POLICY_PATH=/home/njr/AA/ext/ROSRV/config/access-policy.cfg
source devel/setup.bash

progress "Running roscore"
ROS_MASTER_URI="$REAL_MASTER_URI" roscore -p 20022  >/dev/null &
sleep 1

progress "Running rvmaster"
rosrun rvmaster rvmaster >/dev/null &
sleep 1

monitor=testSpecOne
progress "Enabling $monitor"
bin/rosrv.py -enable "$monitor" >/dev/null
bin/rosrv.py -list "$monitor"
sleep 1

progress "Running tests"
pytest ./src/RVMaster/test-monitors.py

kill $(jobs -p)
