#!/usr/bin/env bash
set -e

repo_dir="$(cd "$(dirname "$0")"; pwd)"

progress() { echo ==== "$@" ; }

trap 'cleanup; echo >&2 "FAILED!"' 0
cleanup() {
  progress "Cleaning up"
  kill $(jobs -p) >/dev/null 2>&1 || true
  sleep 1
  kill -9 $(jobs -p) >/dev/null 2>&1 || true
}
clean_exit() {
    cleanup
    trap '' 0
    error_code=$1; shift
    echo >&2 "$@"
    exit $error_code
}

type pytest > /dev/null \
    || clean_exit 1 -e \
            'Please install pytest for python2 via pip.' \
          '\nOn ubuntu xenial run:: `pip2 install pip && pip2 install --user pytest`'

source /opt/ros/kinetic/setup.bash # TODO: This path is Ubuntu specific
export PATH="$(pwd)/src/rosmop/bin:$PATH"

progress "Building rosmop"
(cd src/rosmop ; mvn -q package -DskipTests)

progress "Building src"
catkin build --cmake-args -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON --

test_against_rvmaster() {
    export ROS_MASTER_URI="http://localhost:11311/"
    export REAL_MASTER_URI="http://localhost:20022/"
    export ACCESS_POLICY_PATH="$repo_dir/config/access-policy.cfg"

    progress "Running roscore"
    ROS_MASTER_URI="$REAL_MASTER_URI" roscore -p 20022  >/dev/null &
    sleep 1

    progress "Running rvmaster"
    rosrun rvmaster rvmaster --monitor-topic monitored >/dev/null &
    sleep 1

    progress "Running monitor"
    rosrun rvmonitor test-isolated-monitor >/dev/null & sleep 1

    progress "Running tests"
    pytest t/test-against-rvmaster.py
}

test_without_rvmaster() {
    export ROS_MASTER_URI="http://localhost:20022/"
    export ACCESS_POLICY_PATH="$repo_dir/config/access-policy.cfg"

    progress "Running roscore"
    roscore -p 20022 >/dev/null  &
    sleep 1

    progress "Running monitor"
    rosrun rvmonitor test-isolated-monitor >/dev/null & sleep 1

    progress "Running tests"
    pytest t/test-without-rvmaster.py
}

test_experiment() {
    export ROS_MASTER_URI="http://localhost:20022/"
    export ACCESS_POLICY_PATH="$repo_dir/config/access-policy.cfg"

    progress "Running roscore"
    roscore -p 20022 >/dev/null  &
    sleep 1

    progress "publish"
    rostopic pub chatter std_msgs/String 'Hi /chatter!' & sleep 1

    progress "Running experiment"
    rosrun rvmonitor experiment & sleep 1

    sleep 2
}

source devel/setup.bash
( progress test_against_rvmaster ; test_against_rvmaster )
# ( progress test_without_rvmaster ; test_without_rvmaster )
# ( progress test_experiment
#   test_experiment
# )
# 


clean_exit 0
